### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by praetp** [dragunoff/OpenRA-replay-analytics#1]
spetsnaz@diannao ~/.openra/Replays/ra/release-20191117 $ /usr/local/bin/openra replay-data OpenRA-2019-12-29T103805Z.orarep --format pretty-json 
Traceback (most recent call last):
	7: from /usr/local/bin/openra:23:in `<main>'
	6: from /usr/local/bin/openra:23:in `load'
	5: from /var/lib/gems/2.5.0/gems/openra-1.5.0/bin/openra:6:in `<top (required)>'
	4: from /var/lib/gems/2.5.0/gems/openra-1.5.0/lib/openra/cli.rb:16:in `call'
	3: from /var/lib/gems/2.5.0/gems/hanami-cli-0.2.0/lib/hanami/cli.rb:57:in `call'
	2: from /var/lib/gems/2.5.0/gems/openra-1.5.0/lib/openra/cli/commands/replay_data.rb:16:in `call'
	1: from /var/lib/gems/2.5.0/gems/openra-1.5.0/lib/openra/replays/replay.rb:41:in `global_settings'
/var/lib/gems/2.5.0/gems/openra-1.5.0/lib/openra/replays/replay.rb:59:in `sync_info': bad value for range (ArgumentError)

**Comment by dragunoff** [comment]
This is a crash with the [openra-ruby](https://github.com/AMHOL/openra-ruby) utility and the issue should be filed there. The code in this repo is just a visualization layer that uses data extracted by that utility.
